physical_ai_server:
  ros__parameters:
    ffw_bh5_rev1:
      observation_list:
        - cam_head
        - cam_wrist_left
        - cam_wrist_right
        - state

      camera_topic_list: 
        - cam_head:/zed/zed_node/left/image_rect_color/compressed
        - cam_wrist_left:/camera_left/camera_left/color/image_rect_raw/compressed
        - cam_wrist_right:/camera_right/camera_right/color/image_rect_raw/compressed

      joint_topic_list:
        - follower:/joint_states
        - leader_left:/leader/joint_trajectory_command_broadcaster_left/joint_trajectory
        - leader_right:/leader/joint_trajectory_command_broadcaster_right/joint_trajectory
        - leader_hand_left:/leader/joint_trajectory_command_broadcaster_left_hand/joint_trajectory
        - leader_hand_right:/leader/joint_trajectory_command_broadcaster_right_hand/joint_trajectory

      joint_list:
        - leader_left
        - leader_right
        - leader_hand_left
        - leader_hand_right

      joint_order:
        leader_left:
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7
        leader_right:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
        leader_hand_left:
          - finger_l_joint1
          - finger_l_joint2
          - finger_l_joint3
          - finger_l_joint4
          - finger_l_joint5
          - finger_l_joint6
          - finger_l_joint7
          - finger_l_joint8
          - finger_l_joint9
          - finger_l_joint10
          - finger_l_joint11
          - finger_l_joint12
          - finger_l_joint13
          - finger_l_joint14
          - finger_l_joint15
          - finger_l_joint16
          - finger_l_joint17
          - finger_l_joint18
          - finger_l_joint19
          - finger_l_joint20
        leader_hand_right:
          - finger_r_joint1
          - finger_r_joint2
          - finger_r_joint3
          - finger_r_joint4
          - finger_r_joint5
          - finger_r_joint6
          - finger_r_joint7
          - finger_r_joint8
          - finger_r_joint9
          - finger_r_joint10
          - finger_r_joint11
          - finger_r_joint12
          - finger_r_joint13
          - finger_r_joint14
          - finger_r_joint15
          - finger_r_joint16
          - finger_r_joint17
          - finger_r_joint18
          - finger_r_joint19
          - finger_r_joint20
